//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Images
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int Pic_ID { get; set; }
        public string Name { get; set; }
        public string Size { get; set; }
        public string Type { get; set; }
        public string Desc { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string url { get; set; }
        public string user_email { get; set; }
    }
}
